from __future__ import annotations

import os
import shutil
from pathlib import Path
import pandas as pd

from pipeline.feature_extractor import DySecFeatureExtractor
from pipeline.dysec_predictor import DySecPredictor


# Initialize the predictor and feature extractor using existing trained models
_PREDICTOR = DySecPredictor(model_dir="models/rf")
_EXTRACTOR = DySecFeatureExtractor(schema_path="models/rf/Combined_schema.json")


def _sync_qut_traces_to_extractor_format(trace_dir: Path, package_name: str) -> None:
    """
    Map trace files from the QUT-DV25 directory layout generated by tracer.py
    to the expected log filenames required by DySecFeatureExtractor.
    """
    # 1. Opensnoop log: QUT-DV25_Opensnoop_Traces/* -> <pkg>_opens.log
    opensnoop_dir = trace_dir / "QUT-DV25_Opensnoop_Traces"
    if opensnoop_dir.exists():
        for f in opensnoop_dir.glob("*_opensnoop_trace.txt"):
            shutil.copyfile(f, trace_dir / f"{package_name}_opens.log")
            break

    # 2. TCP log: QUT-DV25_TCP_Traces/* -> <pkg>_tcps.log
    tcp_dir = trace_dir / "QUT-DV25_TCP_Traces"
    if tcp_dir.exists():
        for f in tcp_dir.glob("*_tcptraces.txt"):
            shutil.copyfile(f, trace_dir / f"{package_name}_tcps.log")
            break

    # 3. Installation log: QUT-DV25_Installation_Traces/* -> <pkg>_inst.log
    inst_dir = trace_dir / "QUT-DV25_Installation_Traces"
    if inst_dir.exists():
        for f in inst_dir.glob("*_install_log.txt"):
            shutil.copyfile(f, trace_dir / f"{package_name}_inst.log")
            break

    # 4. Filetop log: QUT-DV25_Filetop_Traces/* -> <pkg>_filetop.log
    filetop_dir = trace_dir / "QUT-DV25_Filetop_Traces"
    if filetop_dir.exists():
        for f in filetop_dir.glob("*_filetop_trace.txt"):
            shutil.copyfile(f, trace_dir / f"{package_name}_filetop.log")
            break

    # 5. Syscall / Pattern Traces -> <pkg>_syscall.log
    pattern_dir = trace_dir / "QUT-DV25_Pattern_Traces"
    if pattern_dir.exists():
        pattern_files = list(pattern_dir.rglob("strace_output_*"))
        if pattern_files:
            # Copy the main per-process strace capture as syscall log
            shutil.copyfile(pattern_files[0], trace_dir / f"{package_name}_syscall.log")


def evaluate_trace(
    trace_path: Path,
) -> dict:
    """
    Complete evaluation flow:
    1. Read and map QUT-DV25 standard logs
    2. Extract 39 features via DySecFeatureExtractor
    3. Infer MALICIOUS / BENIGN via DySecPredictor (Random Forest)
    """
    trace_path = Path(trace_path).resolve()

    if not trace_path.exists():
        raise FileNotFoundError(
            f"Trace directory does not exist: {trace_path}"
        )

    # Resolve package name from directory structure (traces/<package_name>/<strategy>/round_xx)
    try:
        package_name = trace_path.parts[-3]
    except IndexError:
        package_name = "sample_pkg"

    # Step 1: Map logs from QUT-DV25 schema into extractor-compatible files
    _sync_qut_traces_to_extractor_format(trace_path, package_name)

    # Step 2: Extract 39 features into a single-row DataFrame
    df_features = _EXTRACTOR.extract(
        trace_dir=str(trace_path),
        package_name=package_name,
    )

    # Step 3: Run inference through the Random Forest model
    result = _PREDICTOR.predict(df_features)

    # Append runtime metadata for loop.py
    result["trace_directory"] = str(trace_path)
    result["features_extracted"] = int(len(df_features.columns) - 1)  # Exclude Package_Name column
    result["package_name"] = package_name

    return result