from __future__ import annotations

import shutil
from pathlib import Path

from config.settings import (
    OUTPUT_DIR,
    ROUNDS_PER_STRATEGY,
    TRACE_DIR,
    SANDBOX_USER,
    TRACE_WINDOW,
)

from config.strategies import STRATEGIES

from pipeline.package_loader import (
    extract_package,
    collect_python_files,
)

from pipeline.prompt_builder import (
    build_prompt,
)

from pipeline.generator import (
    generate_variant,
)

from pipeline.harness import (
    copy_package,
)

from pipeline.validator import (
    validate_behavior,
)

from pipeline.trace_runner import (
    trace_package,
)

from pipeline.evaluator import (
    evaluate_trace,
)

from pipeline.logger import (
    save_json,
    save_text,
)


def _find_target_source(
    package_root: Path,
) -> Path:

    python_files = collect_python_files(
        package_root
    )

    if not python_files:
        raise RuntimeError(
            f"No Python source files found in "
            f"{package_root}"
        )

    return python_files[0]


def _trace_path(
    package_name: str,
    strategy_name: str,
    round_number: int,
) -> Path:

    return (
        TRACE_DIR
        / package_name
        / strategy_name
        / f"round_{round_number:02d}"
    )


def _cleanup_previous_traces(
    package_name: str,
) -> None:
    """
    Remove traces from previous experiment runs.

    This prevents old round directories from being
    mistaken for traces generated by the current run.
    """

    package_trace_dir = (
        TRACE_DIR
        / package_name
    )

    if package_trace_dir.exists():
        shutil.rmtree(
            package_trace_dir
        )


def run_package(
    package_name: str,
    archive_path: Path,
) -> dict:
    """
    Run the complete DySec robustness experiment
    for one malicious package.

    Main loop:

        Original package
            ↓
        LLM transformation
            ↓
        Behaviour validation
            ↓
        Sandbox installation
            ↓
        eBPF tracing
            ↓
        DySec inference
            ↓
        BENIGN    → STOP
        MALICIOUS → feedback → next round
    """

    archive_path = Path(
        archive_path
    ).resolve()

    # ---------------------------------------------------------
    # Clean previous package output
    # ---------------------------------------------------------

    package_output = (
        OUTPUT_DIR
        / package_name
    )

    if package_output.exists():
        shutil.rmtree(
            package_output
        )

    package_output.mkdir(
        parents=True,
        exist_ok=True,
    )

    # ---------------------------------------------------------
    # Clean previous traces
    # ---------------------------------------------------------

    _cleanup_previous_traces(
        package_name
    )

    # ---------------------------------------------------------
    # Extract original package
    # ---------------------------------------------------------

    original_dir = (
        package_output
        / "original"
    )

    original_root = extract_package(
        archive_path,
        original_dir,
    )

    total_attempts = 0

    # =========================================================
    # STRATEGY LOOP
    # =========================================================

    for strategy in STRATEGIES:

        strategy_name = strategy["name"]

        # Each strategy starts from the ORIGINAL package.
        current_package = original_root

        # Feedback state is reset when changing strategy.
        previous_verdict = None

        feedback_history: list[dict] = []

        # =====================================================
        # ROUND LOOP
        # =====================================================

        for round_number in range(
            1,
            ROUNDS_PER_STRATEGY + 1,
        ):

            total_attempts += 1

            round_dir = (
                package_output
                / strategy_name
                / f"round_{round_number:02d}"
            )

            round_dir.mkdir(
                parents=True,
                exist_ok=True,
            )

            # -------------------------------------------------
            # Find source file
            # -------------------------------------------------

            target_file = _find_target_source(
                current_package
            )

            relative_path = str(
                target_file.relative_to(
                    current_package
                )
            )

            source_code = target_file.read_text(
                encoding="utf-8",
                errors="replace",
            )

            # -------------------------------------------------
            # Build prompt
            # -------------------------------------------------

            prompt = build_prompt(
                strategy=strategy, 
                relative_path=relative_path,
                source_code=source_code,
                round_number=round_number,
                previous_verdict=previous_verdict,
                feedback_history=feedback_history,
            )

            save_text(
                round_dir / "prompt.txt",
                prompt,
            )

            # Save structured feedback information.
            save_json(
                round_dir / "feedback.json",
                {
                    "previous_verdict": (
                        previous_verdict
                    ),
                    "feedback_history": (
                        feedback_history
                    ),
                },
            )

            # -------------------------------------------------
            # LLM generation
            # -------------------------------------------------

            generation = generate_variant(
                prompt
            )

            if not generation["success"]:

                result = {
                    "package": package_name,
                    "strategy": strategy_name,
                    "round": round_number,
                    "status": "GENERATION_ERROR",
                    "behavior_preserved": None,
                    "previous_verdict": (
                        previous_verdict
                    ),
                    "generation": {
                        "tokens": generation.get(
                            "tokens",
                            {},
                        ),
                        "response_metadata": generation.get(
                            "response_metadata",
                            {},
                        ),
                    },
                    "error": generation["error"],
                }

                save_json(
                    round_dir / "result.json",
                    result,
                )

                continue

            # -------------------------------------------------
            # Save generated source
            # -------------------------------------------------

            generated_package = (
                round_dir
                / "package"
            )

            copy_package(
                current_package,
                generated_package,
            )

            generated_target = (
                generated_package
                / relative_path
            )

            generated_target.write_text(
                generation["code"],
                encoding="utf-8",
            )

            save_text(
                round_dir / "generated_code.py",
                generation["code"],
            )

            # -------------------------------------------------
            # Behaviour validation
            # -------------------------------------------------

            behavior = validate_behavior(
                original_package=original_root,
                generated_package=generated_package,
            )

            if not behavior["preserved"]:

                result = {
                    "package": package_name,
                    "strategy": strategy_name,
                    "round": round_number,
                    "status": "BEHAVIOR_NOT_PRESERVED",
                    "behavior_preserved": False,
                    "behavior_validation": behavior,
                    "previous_verdict": (
                        previous_verdict
                    ),
                    "generation": {
                        "tokens": generation.get(
                            "tokens",
                            {},
                        ),
                        "response_metadata": generation.get(
                            "response_metadata",
                            {},
                        ),
                    },
                }

                save_json(
                    round_dir / "result.json",
                    result,
                )

                continue

            # -------------------------------------------------
            # Generate eBPF traces
            # -------------------------------------------------

            trace_directory = _trace_path(
                package_name,
                strategy_name,
                round_number,
            )

            try:

                trace_result = trace_package(
                    package_dir=generated_package,
                    trace_dir=trace_directory,
                    sandbox_user=SANDBOX_USER,
                    window=TRACE_WINDOW,
                )

            except Exception as exc:

                result = {
                    "package": package_name,
                    "strategy": strategy_name,
                    "round": round_number,
                    "status": "TRACING_ERROR",
                    "behavior_preserved": True,
                    "behavior_validation": behavior,
                    "previous_verdict": (
                        previous_verdict
                    ),
                    "generation": {
                        "tokens": generation.get(
                            "tokens",
                            {},
                        ),
                        "response_metadata": generation.get(
                            "response_metadata",
                            {},
                        ),
                    },
                    "error": str(exc),
                }

                save_json(
                    round_dir / "result.json",
                    result,
                )

                continue

            save_json(
                round_dir / "trace_result.json",
                trace_result,
            )

            # -------------------------------------------------
            # Check installation
            # -------------------------------------------------

            if not trace_result["install_success"]:

                result = {
                    "package": package_name,
                    "strategy": strategy_name,
                    "round": round_number,
                    "status": "TRACE_INSTALL_ERROR",
                    "behavior_preserved": True,
                    "behavior_validation": behavior,
                    "trace_result": trace_result,
                    "previous_verdict": (
                        previous_verdict
                    ),
                    "generation": {
                        "tokens": generation.get(
                            "tokens",
                            {},
                        ),
                        "response_metadata": generation.get(
                            "response_metadata",
                            {},
                        ),
                    },
                }

                save_json(
                    round_dir / "result.json",
                    result,
                )

                continue

            # -------------------------------------------------
            # Check trace availability
            # -------------------------------------------------

            if not trace_result["trace_available"]:

                result = {
                    "package": package_name,
                    "strategy": strategy_name,
                    "round": round_number,
                    "status": "NO_TRACE",
                    "behavior_preserved": True,
                    "behavior_validation": behavior,
                    "trace_result": trace_result,
                    "previous_verdict": (
                        previous_verdict
                    ),
                    "generation": {
                        "tokens": generation.get(
                            "tokens",
                            {},
                        ),
                        "response_metadata": generation.get(
                            "response_metadata",
                            {},
                        ),
                    },
                }

                save_json(
                    round_dir / "result.json",
                    result,
                )

                continue

            # -------------------------------------------------
            # DySec inference
            # -------------------------------------------------

            try:

                dysec_result = evaluate_trace(
                    trace_directory
                )

            except Exception as exc:

                result = {
                    "package": package_name,
                    "strategy": strategy_name,
                    "round": round_number,
                    "status": "DYSEC_ERROR",
                    "behavior_preserved": True,
                    "behavior_validation": behavior,
                    "trace_result": trace_result,
                    "previous_verdict": (
                        previous_verdict
                    ),
                    "generation": {
                        "tokens": generation.get(
                            "tokens",
                            {},
                        ),
                        "response_metadata": generation.get(
                            "response_metadata",
                            {},
                        ),
                    },
                    "error": str(exc),
                }

                save_json(
                    round_dir / "result.json",
                    result,
                )

                continue

            # -------------------------------------------------
            # Normalise verdict
            # -------------------------------------------------

            verdict = str(
                dysec_result.get(
                    "verdict",
                    "UNKNOWN",
                )
            ).upper()

            # =================================================
            # BENIGN → STOP
            # =================================================

            if verdict == "BENIGN":

                result = {
                    "package": package_name,
                    "strategy": strategy_name,
                    "round": round_number,
                    "status": "SUCCESSFUL_EVASION",
                    "behavior_preserved": True,
                    "behavior_validation": behavior,
                    "trace_result": trace_result,
                    "dysec_verdict": verdict,
                    "dysec_result": dysec_result,
                    "previous_verdict": (
                        previous_verdict
                    ),
                    "generation": {
                        "tokens": generation.get(
                            "tokens",
                            {},
                        ),
                        "response_metadata": generation.get(
                            "response_metadata",
                            {},
                        ),
                    },
                }

                save_json(
                    round_dir / "result.json",
                    result,
                )

                summary = {
                    **result,
                    "total_attempts": total_attempts,
                }

                save_json(
                    package_output / "summary.json",
                    summary,
                )

                # IMPORTANT:
                # BENIGN means the experiment succeeds.
                # STOP the entire pipeline.
                return summary

            # =================================================
            # MALICIOUS → FEEDBACK LOOP
            # =================================================

            result = {
                "package": package_name,
                "strategy": strategy_name,
                "round": round_number,
                "status": "DETECTED",
                "behavior_preserved": True,
                "behavior_validation": behavior,
                "trace_result": trace_result,
                "dysec_verdict": verdict,
                "dysec_result": dysec_result,
                "previous_verdict": (
                    previous_verdict
                ),
                "generation": {
                    "tokens": generation.get(
                        "tokens",
                        {},
                    ),
                    "response_metadata": generation.get(
                        "response_metadata",
                        {},
                    ),
                },
            }

            save_json(
                round_dir / "result.json",
                result,
            )

            # -------------------------------------------------
            # Update feedback state
            # -------------------------------------------------

            feedback_history.append(
                {
                    "round": round_number,
                    "verdict": verdict,
                }
            )

            previous_verdict = verdict

            # -------------------------------------------------
            # IMPORTANT:
            #
            # The next round must use the generated package
            # that was just detected as MALICIOUS.
            # -------------------------------------------------

            current_package = generated_package

    # =========================================================
    # ALL STRATEGIES EXHAUSTED
    # =========================================================

    summary = {
        "package": package_name,
        "strategy": None,
        "round": None,
        "status": "ALL_STRATEGIES_EXHAUSTED",
        "total_attempts": total_attempts,
        "dysec_verdict": None,
    }

    save_json(
        package_output / "summary.json",
        summary,
    )

    return summary