from __future__ import annotations

import argparse
import json
import os
import pwd
import shutil
import signal
import subprocess
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List, Optional


# ============================================================================
# Paths
# ============================================================================

PROJECT_ROOT = Path(__file__).resolve().parent.parent

TRACE_ENGINE_DIR = PROJECT_ROOT / "trace_engine"
DEFAULT_TRACE_OUTPUT = PROJECT_ROOT / "output_data" / "traces"


# ============================================================================
# DySec trace families
#
# DySec has six dynamic-analysis trace families:
#
#   1. FiletopTraces
#   2. InstallTraces
#   3. OpensnoopTraces
#   4. TCPTraces
#   5. SystemCallTraces
#   6. PatternTraces
#
# Five families are generated by bpftrace probes.
# InstallTraces are generated from the pip installation output.
# ============================================================================

BPFTRACE_PROBES = {
    "filetop": "filetop.bt",
    "opensnoop": "opensnoop.bt",
    "tcp": "tcp.bt",
    "syscount": "syscount.bt",
    "syscall_sequence": "syscall_sequence.bt",
}


TRACE_FAMILIES = (
    "filetop",
    "install",
    "opensnoop",
    "tcp",
    "syscount",
    "syscall_sequence",
)


# ============================================================================
# Result
# ============================================================================

@dataclass
class TraceResult:
    package_dir: str
    trace_dir: str

    # Deployment
    deploy_success: bool

    # Installation
    install_return_code: Optional[int]
    install_success: bool

    # Trace status
    trace_available: bool
    valid_trace: bool
    partial_trace: bool

    # Probe / validation errors
    probe_errors: List[str]

    # Timing
    started_at: float
    finished_at: float
    duration_seconds: float

    # Generated trace files
    trace_files: Dict[str, str]

    # Human-readable diagnostic information
    notes: str = ""


# ============================================================================
# System checks
# ============================================================================

def require_root() -> None:
    """bpftrace normally requires root privileges."""
    if os.geteuid() != 0:
        raise PermissionError(
            "This tracer must be run as root because bpftrace "
            "requires privileged access."
        )


def check_command(command: str) -> None:
    """Make sure an external command exists."""
    if shutil.which(command) is None:
        raise FileNotFoundError(
            f"Required command '{command}' was not found in PATH."
        )


def resolve_sandbox_user(username: str) -> tuple[int, int]:
    """Return (uid, gid) for the sandbox user."""
    try:
        user = pwd.getpwnam(username)
    except KeyError as exc:
        raise RuntimeError(
            f"Sandbox user '{username}' does not exist."
        ) from exc

    return user.pw_uid, user.pw_gid


def validate_probe_files(probe_dir: Path) -> None:
    """Verify that all five bpftrace probe files exist."""
    missing: List[str] = []

    for filename in BPFTRACE_PROBES.values():
        path = probe_dir / filename

        if not path.is_file():
            missing.append(str(path))

    if missing:
        raise FileNotFoundError(
            "Missing bpftrace probe files:\n"
            + "\n".join(f"  - {path}" for path in missing)
        )


# ============================================================================
# Privilege dropping
# ============================================================================

def set_process_identity(uid: int, gid: int):
    """
    Return a preexec function that drops privileges to the sandbox user.

    bpftrace itself remains root.
    Package installation runs as the unprivileged sandbox user.
    """

    def _set_identity() -> None:
        os.setgid(gid)
        os.setuid(uid)

        user = pwd.getpwuid(uid)

        os.environ["HOME"] = user.pw_dir
        os.environ["USER"] = user.pw_name

        os.environ["PATH"] = (
            "/usr/local/sbin:"
            "/usr/local/bin:"
            "/usr/sbin:"
            "/usr/bin:"
            "/sbin:"
            "/bin"
        )

        os.environ["LANG"] = "C"
        os.environ["LC_ALL"] = "C"

    return _set_identity


# ============================================================================
# Probe management
# ============================================================================

class ProbeSet:
    """
    Manage the five DySec bpftrace probes.

    The probes are intentionally started before package installation.

    Each probe is scoped to the sandbox UID:

        bpftrace <probe.bt> <sandbox_uid>

    This prevents unrelated system activity from becoming part of the
    package trace.
    """

    def __init__(
        self,
        trace_dir: Path,
        sandbox_uid: int,
        probe_dir: Path,
    ):
        self.trace_dir = trace_dir
        self.sandbox_uid = sandbox_uid
        self.probe_dir = probe_dir

        self.processes: Dict[str, subprocess.Popen] = {}
        self.output_files: Dict[str, object] = {}

        self.trace_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

    def start(self) -> None:
        """
        Start all five probes and verify that every process remains alive.
        """

        for name, script_name in BPFTRACE_PROBES.items():

            script_path = self.probe_dir / script_name

            if not script_path.is_file():
                raise FileNotFoundError(
                    f"Probe script missing: {script_path}"
                )

            output_path = (
                self.trace_dir / f"{name}.trace"
            )

            output_file = open(
                output_path,
                "w",
                encoding="utf-8",
            )

            command = [
                "bpftrace",
                str(script_path),
                str(self.sandbox_uid),
            ]

            print(
                f"[Tracer] Starting probe: {name}"
            )

            print(
                "          "
                + " ".join(command)
            )

            try:
                process = subprocess.Popen(
                    command,
                    stdout=output_file,
                    stderr=subprocess.STDOUT,
                    start_new_session=True,
                )
            except Exception:
                output_file.close()
                raise

            self.processes[name] = process
            self.output_files[name] = output_file

        # Allow bpftrace to compile and attach.
        time.sleep(3.0)

        dead_probes: List[str] = []

        for name, process in self.processes.items():

            return_code = process.poll()

            if return_code is not None:

                dead_probes.append(
                    f"{name}: bpftrace exited before installation "
                    f"(return code {return_code})"
                )

        if dead_probes:

            self.stop()

            raise RuntimeError(
                "One or more bpftrace probes failed to start:\n"
                + "\n".join(dead_probes)
            )

        print(
            "[Tracer] All five bpftrace probes are running."
        )

    def stop(self, timeout: int = 12) -> List[str]:
        """
        Stop probes using SIGINT.

        SIGINT is important because bpftrace prints accumulated map data
        when it terminates normally.
        """

        errors: List[str] = []

        if not self.processes:
            return errors

        print(
            "[Tracer] Sending SIGINT to bpftrace probes..."
        )

        for name, process in self.processes.items():

            if process.poll() is not None:
                continue

            try:
                os.killpg(
                    process.pid,
                    signal.SIGINT,
                )

            except ProcessLookupError:
                pass

            except Exception as exc:
                errors.append(
                    f"{name}: failed to send SIGINT: {exc}"
                )

        deadline = time.time() + timeout

        for name, process in self.processes.items():

            remaining = max(
                0.1,
                deadline - time.time(),
            )

            try:
                process.wait(
                    timeout=remaining
                )

            except subprocess.TimeoutExpired:

                errors.append(
                    f"{name}: did not terminate after SIGINT"
                )

                try:
                    os.killpg(
                        process.pid,
                        signal.SIGKILL,
                    )

                except ProcessLookupError:
                    pass

                except Exception as exc:
                    errors.append(
                        f"{name}: SIGKILL failed: {exc}"
                    )

                try:
                    process.wait(timeout=2)

                except subprocess.TimeoutExpired:

                    errors.append(
                        f"{name}: failed to terminate"
                    )

        # Close files after bpftrace has finished writing.
        for output_file in self.output_files.values():

            try:
                output_file.close()

            except Exception:
                pass

        self.processes.clear()
        self.output_files.clear()

        return errors


# ============================================================================
# Local package deployment
# ============================================================================

def prepare_local_package(
    package_dir: Path,
    destination: Path,
    uid: int,
    gid: int,
) -> bool:
    """
    Local equivalent of DySec Deploy(pi_j, d_k).

    Current robustness mode:

        generated package
              |
              v
        sandbox workspace

    Later, a PyPI deployment function can be added without changing the
    ProbeSet or trace collection logic.
    """

    if not package_dir.exists():
        return False

    if not package_dir.is_dir():
        return False

    if destination.exists():
        shutil.rmtree(
            destination,
            ignore_errors=True,
        )

    destination.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    shutil.copytree(
        package_dir,
        destination,
    )

    for path in [
        destination,
        *destination.rglob("*"),
    ]:
        os.chown(
            path,
            uid,
            gid,
        )

    return True


# ============================================================================
# Virtual environment
# ============================================================================

def create_environment(
    work_dir: Path,
    uid: int,
    gid: int,
) -> Path:
    """
    Create a completely fresh virtual environment.

    A fresh environment is used for every trace invocation.
    """

    env_dir = work_dir / ".trace_env"

    if env_dir.exists():
        shutil.rmtree(
            env_dir,
            ignore_errors=True,
        )

    env_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    os.chown(
        env_dir,
        uid,
        gid,
    )

    command = [
        "python3",
        "-m",
        "venv",
        "--system-site-packages",
        str(env_dir),
    ]

    print(
        "[Tracer] Creating fresh virtual environment..."
    )

    result = subprocess.run(
        command,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        preexec_fn=set_process_identity(
            uid,
            gid,
        ),
        timeout=60,
    )

    if result.returncode != 0:

        raise RuntimeError(
            "Failed to create virtual environment.\n"
            f"{result.stdout}"
        )

    python_path = env_dir / "bin" / "python"
    pip_path = env_dir / "bin" / "pip"

    if not python_path.exists():

        raise RuntimeError(
            "Virtual environment was created but "
            f"Python was not found: {python_path}"
        )

    if not pip_path.exists():

        raise RuntimeError(
            "Virtual environment was created but "
            f"pip was not found: {pip_path}"
        )

    return env_dir


# ============================================================================
# Local installation
# ============================================================================

def install_local_package(
    package_dir: Path,
    env_dir: Path,
    uid: int,
    gid: int,
    timeout: int,
) -> subprocess.CompletedProcess:
    """
    Install the generated local package.

    Important:

        --no-deps
            Do not pull external dependencies.

        --no-index
            Do not contact PyPI.

        --no-build-isolation
            Prevent pip from creating an isolated build environment.

    This is specifically useful for the current local robustness
    experiment.

    For future PyPI mode, this function can be replaced by a PyPI
    installer while the tracing engine remains unchanged.
    """

    pip_path = env_dir / "bin" / "pip"

    command = [
        str(pip_path),
        "install",
        "--no-input",
        "--no-deps",
        "--no-index",
        "--no-build-isolation",
        str(package_dir),
    ]

    print(
        "[Tracer] Running installation:"
    )

    print(
        "          "
        + " ".join(command)
    )

    return subprocess.run(
        command,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        preexec_fn=set_process_identity(
            uid,
            gid,
        ),
        timeout=timeout,
    )


# ============================================================================
# InstallTraces
# ============================================================================

def save_install_trace(
    trace_dir: Path,
    install_output: str,
) -> Path:
    """
    Save pip installation output as the sixth DySec trace family.

    This corresponds to:

        InstallTraces

    It is intentionally named install.trace so that the complete trace
    directory contains all six dynamic-analysis families.
    """

    path = trace_dir / "install.trace"

    path.write_text(
        install_output or "",
        encoding="utf-8",
    )

    return path


# ============================================================================
# Trace collection
# ============================================================================

def collect_trace_files(
    trace_dir: Path,
) -> Dict[str, str]:
    """
    Collect all six trace families.

    The five bpftrace files are generated by the probes.
    install.trace is generated from pip installation output.
    """

    trace_files: Dict[str, str] = {}

    for family in TRACE_FAMILIES:

        path = trace_dir / f"{family}.trace"

        if path.is_file():

            trace_files[family] = str(path)

    return trace_files


def validate_trace_files(
    trace_files: Dict[str, str],
) -> tuple[bool, List[str]]:
    """
    Validate that all six trace families exist and contain data.

    A file that exists but is empty is treated as invalid.
    """

    errors: List[str] = []

    for family in TRACE_FAMILIES:

        path_string = trace_files.get(family)

        if path_string is None:

            errors.append(
                f"Missing trace family: {family}"
            )

            continue

        path = Path(path_string)

        if not path.exists():

            errors.append(
                f"Trace file does not exist: {path}"
            )

            continue

        if path.stat().st_size == 0:

            errors.append(
                f"Trace file is empty: {path}"
            )

    return (
        len(errors) == 0,
        errors,
    )


# ============================================================================
# Result persistence
# ============================================================================

def save_result(
    result: TraceResult,
) -> None:
    """
    Save a machine-readable result.json next to the traces.
    """

    result_path = (
        Path(result.trace_dir)
        / "trace_result.json"
    )

    result_path.write_text(
        json.dumps(
            asdict(result),
            indent=2,
        ),
        encoding="utf-8",
    )


# ============================================================================
# Single trace invocation
# ============================================================================

def trace_package(
    package_dir: Path,
    trace_dir: Path,
    work_dir: Path,
    uid: int,
    gid: int,
    probe_dir: Path,
    post_install_window: int,
    install_timeout: int,
) -> TraceResult:
    """
    Perform exactly one DySec-style trace invocation.

    No strategy information.
    No round information.
    No retry logic.
    No evasion decision.

    The robustness controller decides what happens after this result.
    """

    started_at = time.time()

    deploy_success = False

    install_return_code: Optional[int] = None
    install_success = False

    trace_files: Dict[str, str] = {}
    probe_errors: List[str] = []

    notes: List[str] = []

    env_dir: Optional[Path] = None
    probe_set: Optional[ProbeSet] = None

    sandbox_package_dir = (
        work_dir / package_dir.name
    )

    try:

        # ==================================================================
        # 1. Fresh workspace
        # ==================================================================

        if work_dir.exists():

            shutil.rmtree(
                work_dir,
                ignore_errors=True,
            )

        work_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        os.chown(
            work_dir,
            uid,
            gid,
        )

        # ==================================================================
        # 2. Fresh environment
        # ==================================================================

        env_dir = create_environment(
            work_dir=work_dir,
            uid=uid,
            gid=gid,
        )

        # ==================================================================
        # 3. Deploy package
        # ==================================================================

        print(
            "[Tracer] Deploying local package..."
        )

        deploy_success = prepare_local_package(
            package_dir=package_dir,
            destination=sandbox_package_dir,
            uid=uid,
            gid=gid,
        )

        if not deploy_success:

            notes.append(
                "Local package deployment failed."
            )

            return TraceResult(
                package_dir=str(package_dir),
                trace_dir=str(trace_dir),
                deploy_success=False,
                install_return_code=None,
                install_success=False,
                trace_available=False,
                valid_trace=False,
                partial_trace=False,
                probe_errors=[],
                started_at=started_at,
                finished_at=time.time(),
                duration_seconds=time.time() - started_at,
                trace_files={},
                notes=" ".join(notes),
            )

        # ==================================================================
        # 4. Start probes BEFORE installation
        # ==================================================================

        probe_set = ProbeSet(
            trace_dir=trace_dir,
            sandbox_uid=uid,
            probe_dir=probe_dir,
        )

        probe_set.start()

        # ==================================================================
        # 5. Install package
        # ==================================================================

        install_output = ""

        print(
            "[Tracer] Installing package..."
        )

        try:

            result = install_local_package(
                package_dir=sandbox_package_dir,
                env_dir=env_dir,
                uid=uid,
                gid=gid,
                timeout=install_timeout,
            )

            install_return_code = result.returncode

            install_success = (
                result.returncode == 0
            )

            install_output = (
                result.stdout or ""
            )

            print(
                f"[Tracer] pip return code: "
                f"{result.returncode}"
            )

            if install_output:

                print(
                    "[Tracer] pip output:"
                )

                print(
                    install_output
                )

        except subprocess.TimeoutExpired as exc:

            install_return_code = None
            install_success = False

            timeout_output = ""

            if exc.stdout:
                timeout_output = str(
                    exc.stdout
                )

            install_output = (
                "INSTALL TIMEOUT\n"
                + timeout_output
            )

            notes.append(
                f"Installation exceeded "
                f"{install_timeout}s timeout."
            )

        # ==================================================================
        # 6. InstallTraces
        # ==================================================================

        install_trace = save_install_trace(
            trace_dir=trace_dir,
            install_output=install_output,
        )

        print(
            "[Tracer] Install trace:"
            f" {install_trace}"
        )

        # ==================================================================
        # 7. Observation window
        # ==================================================================

        print(
            f"[Tracer] Observing package behaviour "
            f"for {post_install_window}s..."
        )

        time.sleep(
            post_install_window
        )

    finally:

        # ==================================================================
        # 8. Stop bpftrace probes
        # ==================================================================

        if probe_set is not None:

            print(
                "[Tracer] Stopping bpftrace probes..."
            )

            probe_errors.extend(
                probe_set.stop()
            )

            print(
                "[Tracer] Probes stopped."
            )

        # ==================================================================
        # 9. Remove environment
        # ==================================================================

        if env_dir is not None:

            print(
                "[Tracer] Removing trace environment..."
            )

            shutil.rmtree(
                env_dir,
                ignore_errors=True,
            )

    # ==========================================================================
    # 10. Collect traces
    # ==========================================================================

    trace_files = collect_trace_files(
        trace_dir
    )

    trace_structure_valid, trace_validation_errors = (
        validate_trace_files(
            trace_files
        )
    )

    probe_errors.extend(
        trace_validation_errors
    )

    trace_available = (
        len(trace_files) > 0
    )

    # ==========================================================================
    # 11. Determine trace validity
    # ==========================================================================

    #
    # IMPORTANT:
    #
    # trace_available:
    #     At least one trace exists.
    #
    # valid_trace:
    #     Package deployed successfully
    #     AND installation succeeded
    #     AND all six trace families exist
    #     AND no probe/validation errors exist.
    #
    # partial_trace:
    #     Some useful trace information exists, but the complete valid
    #     trace conditions were not satisfied.
    #

    valid_trace = (
        deploy_success
        and install_success
        and trace_structure_valid
        and not probe_errors
    )

    partial_trace = (
        deploy_success
        and trace_available
        and not valid_trace
    )

    if valid_trace:

        notes.append(
            "Complete DySec-style trace obtained."
        )

    elif partial_trace:

        notes.append(
            "Partial trace retained for debugging, "
            "but it is not a valid trace for robustness "
            "classification."
        )

    elif not deploy_success:

        notes.append(
            "Package deployment failed."
        )

    elif not install_success:

        notes.append(
            "Package installation failed."
        )

    else:

        notes.append(
            "Trace validation failed."
        )

    finished_at = time.time()

    result = TraceResult(
        package_dir=str(package_dir),
        trace_dir=str(trace_dir),

        deploy_success=deploy_success,

        install_return_code=install_return_code,
        install_success=install_success,

        trace_available=trace_available,
        valid_trace=valid_trace,
        partial_trace=partial_trace,

        probe_errors=probe_errors,

        started_at=started_at,
        finished_at=finished_at,

        duration_seconds=(
            finished_at - started_at
        ),

        trace_files=trace_files,

        notes=" ".join(notes),
    )

    save_result(result)

    return result


# ============================================================================
# Public tracer
# ============================================================================

class LocalPackageTracer:
    """
    DySec-style tracer for locally generated packages.

    Architecture:

        generated package
                |
                v
        fresh workspace
                |
                v
        fresh virtualenv
                |
                v
        deploy package
                |
                v
        start 5 bpftrace probes
                |
                v
        pip install
                |
                +----> install.trace
                |
                v
        observe behaviour
                |
                v
        stop probes
                |
                v
        5 bpftrace traces
                |
                v
        6 trace families total

    This class deliberately does NOT know about:

        strategy_A
        strategy_B
        strategy_C
        round
        evasion
        DySec prediction

    Those belong to the robustness pipeline.
    """

    def __init__(
        self,
        trace_output_dir: Path = DEFAULT_TRACE_OUTPUT,
        probe_dir: Path = TRACE_ENGINE_DIR,
        sandbox_user: str = "dysec",
        post_install_window: int = 120,
        install_timeout: int = 180,
    ):

        self.trace_output_dir = Path(
            trace_output_dir
        )

        self.probe_dir = Path(
            probe_dir
        )

        self.sandbox_user = sandbox_user

        self.post_install_window = (
            post_install_window
        )

        self.install_timeout = (
            install_timeout
        )

        require_root()

        check_command(
            "bpftrace"
        )

        check_command(
            "python3"
        )

        validate_probe_files(
            self.probe_dir
        )

        (
            self.sandbox_uid,
            self.sandbox_gid,
        ) = resolve_sandbox_user(
            sandbox_user
        )

    def trace(
        self,
        package_dir: str | Path,
        trace_name: Optional[str] = None,
    ) -> TraceResult:
        """
        Trace exactly one package once.

        Retry/round logic belongs outside this class.
        """

        package_dir = Path(
            package_dir
        ).resolve()

        if not package_dir.exists():

            raise FileNotFoundError(
                f"Package directory does not exist: "
                f"{package_dir}"
            )

        if not package_dir.is_dir():

            raise NotADirectoryError(
                f"Package path is not a directory: "
                f"{package_dir}"
            )

        if trace_name is None:

            trace_name = package_dir.name

        trace_root = (
            self.trace_output_dir
            / trace_name
        )

        if trace_root.exists():

            shutil.rmtree(
                trace_root,
                ignore_errors=True,
            )

        trace_root.mkdir(
            parents=True,
            exist_ok=True,
        )

        os.chown(
            trace_root,
            self.sandbox_uid,
            self.sandbox_gid,
        )

        work_dir = (
            trace_root
            / "workspace"
        )

        print()
        print(
            "=" * 70
        )

        print(
            "DYSEC TRACE"
        )

        print(
            "=" * 70
        )

        print(
            f"Package: {package_dir}"
        )

        print(
            f"Output:  {trace_root}"
        )

        print(
            "=" * 70
        )

        result = trace_package(
            package_dir=package_dir,
            trace_dir=trace_root,
            work_dir=work_dir,
            uid=self.sandbox_uid,
            gid=self.sandbox_gid,
            probe_dir=self.probe_dir,
            post_install_window=self.post_install_window,
            install_timeout=self.install_timeout,
        )

        return result


# ============================================================================
# CLI
# ============================================================================

def main() -> int:

    parser = argparse.ArgumentParser(
        description=(
            "Run one DySec-style dynamic trace extraction "
            "on a local Python package."
        )
    )

    parser.add_argument(
        "package_dir",
        help=(
            "Path to the local Python package directory."
        ),
    )

    parser.add_argument(
        "--output",
        default=str(
            DEFAULT_TRACE_OUTPUT
        ),
        help=(
            "Directory where traces are stored."
        ),
    )

    parser.add_argument(
        "--probe-dir",
        default=str(
            TRACE_ENGINE_DIR
        ),
        help=(
            "Directory containing the five .bt probe files."
        ),
    )

    parser.add_argument(
        "--sandbox-user",
        default="dysec",
        help=(
            "Linux user used for package deployment "
            "and installation."
        ),
    )

    parser.add_argument(
        "--window",
        type=int,
        default=120,
        help=(
            "Post-install observation window in seconds."
        ),
    )

    parser.add_argument(
        "--install-timeout",
        type=int,
        default=180,
        help=(
            "Maximum package installation time in seconds."
        ),
    )

    parser.add_argument(
        "--trace-name",
        default=None,
        help=(
            "Name of the trace output directory."
        ),
    )

    args = parser.parse_args()

    try:

        tracer = LocalPackageTracer(
            trace_output_dir=Path(
                args.output
            ),

            probe_dir=Path(
                args.probe_dir
            ),

            sandbox_user=args.sandbox_user,

            post_install_window=(
                args.window
            ),

            install_timeout=(
                args.install_timeout
            ),
        )

        result = tracer.trace(
            package_dir=args.package_dir,
            trace_name=args.trace_name,
        )

    except Exception as exc:

        print(
            f"[x] {type(exc).__name__}: {exc}",
            file=sys.stderr,
        )

        return 1

    # =========================================================================
    # Final result
    # =========================================================================

    print()
    print(
        "=" * 70
    )

    print(
        "TRACE RESULT"
    )

    print(
        "=" * 70
    )

    print(
        f"Package:          {result.package_dir}"
    )

    print(
        f"Trace directory:  {result.trace_dir}"
    )

    print(
        f"Deploy success:   {result.deploy_success}"
    )

    print(
        f"Install success:  {result.install_success}"
    )

    print(
        f"Install return:   {result.install_return_code}"
    )

    print(
        f"Trace available:  {result.trace_available}"
    )

    print(
        f"Valid trace:      {result.valid_trace}"
    )

    print(
        f"Partial trace:    {result.partial_trace}"
    )

    print(
        f"Duration:         "
        f"{result.duration_seconds:.2f}s"
    )

    print()

    print(
        "Trace families:"
    )

    for family in TRACE_FAMILIES:

        path = result.trace_files.get(
            family
        )

        if path:

            size = Path(path).stat().st_size

            print(
                f"  {family:20s} "
                f"{size:10d} bytes  {path}"
            )

        else:

            print(
                f"  {family:20s} "
                f"MISSING"
            )

    if result.probe_errors:

        print()

        print(
            "Trace / probe errors:"
        )

        for error in result.probe_errors:

            print(
                f"  - {error}"
            )

    if result.notes:

        print()

        print(
            f"Notes: {result.notes}"
        )

    print(
        "=" * 70
    )

    # The caller must inspect valid_trace.
    # A failed package installation is not a tracer crash.
    return 0


if __name__ == "__main__":
    raise SystemExit(
        main()
    )